#! /usr/bin/env/python
import cv2
import os
import moviepy.editor as mpy 
import click

@click.group()
def main():
    pass


@main.command()
@click.option('-i', '--input-path')
@click.option('-o', '--output-path', default='')
def video2frame(input_path, output_path):
    if output_path == '':
        output_path = os.path.splitext(input_path)[0]
    os.makedirs(output_path, exist_ok=True)

    for i, frame in enumerate(mpy.VideoFileClip(input_path).iter_frames()):
        cv2.imwrite(f'{output_path}/{i:03d}.png', frame[..., ::-1])

    print(f'Save to {output_path}')


if __name__ == '__main__':
    main()